/**
 * Generates a 3-letter abbreviation from a project name
 * Takes the first letter of each word, or first 3 consonants/vowels if less than 3 words
 */
export function generateProjectAbbreviation(projectName: string): string {
  if (!projectName || projectName.trim().length === 0) {
    return 'PRJ'; // Default abbreviation
  }

  // Remove special characters and split into words
  const words = projectName
    .trim()
    .replace(/[^\w\s]/g, '') // Remove special characters
    .split(/\s+/)
    .filter(word => word.length > 0);

  // If we have 3 or more words, take first letter of first 3 words
  if (words.length >= 3) {
    return words
      .slice(0, 3)
      .map(word => word[0].toUpperCase())
      .join('');
  }

  // If we have 2 words, take first letter of each
  if (words.length === 2) {
    const first = words[0][0].toUpperCase();
    const second = words[1][0].toUpperCase();
    // Take first consonant or vowel from second word if needed
    const third = words[1].length > 1 ? words[1][1].toUpperCase() : words[0].length > 1 ? words[0][1].toUpperCase() : 'X';
    return first + second + third;
  }

  // If we have 1 word, take first 3 letters (prioritize consonants)
  if (words.length === 1) {
    const word = words[0].toUpperCase();
    if (word.length >= 3) {
      return word.substring(0, 3);
    }
    // Pad with 'X' if less than 3 characters
    return word.padEnd(3, 'X');
  }

  return 'PRJ'; // Fallback
}

/**
 * Generates project number for internal projects
 * Format: concernID + 3-letter abbreviation
 * Example: DE689E0F2D-ADM
 */
export function generateInternalProjectNumber(
  concernID: string,
  projectName: string
): string {
  const abbreviation = generateProjectAbbreviation(projectName);
  return `${concernID}-${abbreviation}`;
}

/**
 * Generates project number for external projects
 * Format: PRJ-YYYYMMDD-HHMMSS (timestamp-based)
 * Or can be customized by user
 */
export function generateExternalProjectNumber(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hours = String(now.getHours()).padStart(2, '0');
  const minutes = String(now.getMinutes()).padStart(2, '0');
  const seconds = String(now.getSeconds()).padStart(2, '0');
  
  return `PRJ-${year}${month}${day}-${hours}${minutes}${seconds}`;
}

/**
 * Checks if a project number is auto-generated (for external projects)
 */
export function isAutoGeneratedProjectNumber(projectNumber: string): boolean {
  return projectNumber.startsWith('PRJ-') && projectNumber.length === 20;
}







